name: Documentation
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install @adobe/jsonschema2md
        run: npm install -g @adobe/jsonschema2md
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
